### ISSUE TITLE
star rating: add hover state to the stars

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-store#1181]
would be nice to have a hover state for the stars

example: 

https://user-images.githubusercontent.com/36884067/227187124-7d26e17a-cdfa-4f3b-873d-17109017f073.mov

**Comment by anasereijo** [comment]
I creeated this issue for the stars on the AppPage level. Unfortunately, with ODRS we can't have the star ratings outside the review modal. However, I think we could still try the animation on the modal? WDYT @jpnurmi

**Comment by anasereijo** [comment]
@jpnurmi sorry, just realised that my comment was confusing 😅

> @anasereijo Do you mean that you'd like the star rating to react without pressing? 

yes, I'd like the stars to be filled on hover, not just on dragging.

> There's also some sort of glow effect that appears when doing so. :)

I think the glow doesn't look quite right. I much prefer to keep it simple, without it. What do you think?

**Comment by anasereijo** [comment]
This is not a biggie, so if too much of a hassle, we don't have to do the hover 👍

**Comment by dejvizelo** [comment]
@anasereijo I was able to solve this in my PR, it is now ready for review
